basePath: /
definitions:
  helpers.Errors:
    properties:
      code:
        type: integer
      errors:
        items:
          type: string
        type: array
      status:
        type: boolean
    type: object
  helpers.Response:
    properties:
      code:
        type: integer
      data: {}
      status:
        type: boolean
    type: object
  models.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      google_id:
        type: string
      id:
        type: integer
      password:
        type: string
      uid:
        type: string
      updated_at:
        type: string
    type: object
  payload.SessionGooglePayload:
    properties:
      access_token:
        type: string
      code:
        type: string
      redirect_url:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: ryudelta7@gmail.com
    name: Ryudelta Support
    url: https://t.me/Grafiters
  description: This is a sample server for a Fiber application.
  license:
    name: MIT
    url: https://github.com/Grafiters/go-archive/tree/main/license
  termsOfService: http://swagger.io/terms/
  title: Fiber Swagger Example API
  version: "10.0"
paths:
  /api/v2/account:
    get:
      consumes:
      - application/json
      description: Get account detail
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/helpers.Response'
            - properties:
                data:
                  $ref: '#/definitions/models.User'
              type: object
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/helpers.Errors'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helpers.Errors'
      summary: Account
      tags:
      - Account
  /api/v2/session:
    post:
      consumes:
      - application/json
      description: Generate session user
      parameters:
      - description: session request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/payload.SessionGooglePayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helpers.Response'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/helpers.Errors'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helpers.Errors'
      summary: Authenticate
      tags:
      - Auth
swagger: "2.0"
