basePath: /v2
definitions:
  interfaces.PaginationParam:
    properties:
      limit:
        description: 'Limit is the maximum number of items per page (default: 10)'
        type: integer
      page:
        description: 'Page Number of items in page (default: 1)'
        type: integer
    type: object
host: petstore.swagger.io
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /:
    get:
      description: This is the root endpoint.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Welcome to Buffalo
      tags:
      - Default
  /public:
    get:
      description: This is the hello endpoint.
      parameters:
      - description: 'Ordering item by request (default: id)'
        in: query
        name: orderby
        type: string
      - description: 'Sorting item by ascending or descending (default: asc)'
        in: query
        name: sortby
        type: string
      - description: 'Limit is the maximum number of items per page (default: 10)'
        in: query
        name: limit
        type: integer
      - description: 'Page Number of items in page (default: 1)'
        in: query
        name: page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/interfaces.PaginationParam'
      summary: Say hello to Buffalo
      tags:
      - Public
swagger: "2.0"
